### PR TITLE
[text, font] Bump go-text version to 0.2.0

### PR DESCRIPTION
**Pull request by benoitkugler**
This PR dumps go-text version to 0.2.0

Some tests are failing, I'm not sure why. The only significant difference (from the last version) I've found is this [commit](https://github.com/go-text/typesetting/pull/130/commits/fea6bbb62b29ef5d526cedab5eadb371e9c6bebc)

### CODE REVIEW

**Comment by whereswaldon** [comment]
Hi @benoitkugler ! Prompted (probably) by the same post in slack, I've been looking at this today too. It seems that [this PR](https://github.com/go-text/typesetting/pull/103/files) is not actually bidi-aware, though I didn't notice when I reviewed it. As a result, we end up trimming spaces within the center of lines when the bidi ordering puts the last logical run within the middle of the line. I'm working on a fix.

**Comment by whereswaldon** [comment]
See https://github.com/go-text/typesetting/pull/175

**Review by whereswaldon — COMMENTED** [review]
The API conversion looks identical to what I tried; we can definitely merge this version. We'll just need to resolve [this PR](https://github.com/go-text/typesetting/pull/175)'s underlying problem before we can proceed, as we otherwise regress on the display of bidi text.

**Comment by whereswaldon** [comment]
@benoitkugler Everything is ready to go except that we need you to sign-off your commit. Sorry I didn't ask for that earlier; I didn't notice, and our CI no longer runs for GitHub pull requests.

**Comment by benoitkugler** [comment]
>  Everything is ready to go except that we need you to sign-off your commit. 

I'm afraid I do not know how to proceed. I've tried `git rebase --signoff ` but it failed. Perhaps it is easier if we drop this PR and use your own local branch ? (If you don't have to manually do the refactoring ?)

**Comment by whereswaldon** [comment]
You can do a `git rebase -i origin/main` (assuming origin points to upstream Gio) and then mark your commit with an `e` for `edit`. Save and quit that interactive rebase file, and you can then run `git commit --amend -s` to sign off the commit.

**Comment by benoitkugler** [comment]
I've followed your tip and I _think_ the commits are now properly signed off.

**Comment by whereswaldon** [comment]
Thanks! Merged.

```
To git.sr.ht:~eliasnaur/gio
   1d95c7c6..e025ed13  main -> main
   ```

**Pull request closed without merging**
