### PR TITLE
app: [iOS] add ViewController on ViewEvent

### PR DESCRIPTION
**Pull request by Inkeliz**
New "ViewController" field on ViewEvent, which contain UIViewController for
iOS. That is necessary to open custom UIViewController on top of Gio.

### CODE REVIEW

**Comment by eliasnaur** [comment]
Can the ViewController be inferred from the View (e.g. through a method on UIVIew)?

Conversely, do we need View if we add ViewController?

**Comment by Inkeliz** [comment]
I don't find any way to get the Controller from the View. But, it's seens possible to get the UIView from the UIViewController (https://developer.apple.com/documentation/uikit/uiviewcontroller/1621460-view?language=objc).

**Comment by whereswaldon** [comment]
Can we then simplify to only providing the controller in the `ViewEvent` instead of both?

**Comment by Inkeliz** [comment]
I force-push to remove the `View`. But, should keep the name `View` or change to `ViewController` (since it's `UIViewController now)?

**Comment by whereswaldon** [comment]
Let's use the most descriptive name we can (`ViewController`), and let's include a link to "how to get the view from the viewcontroller" in the documentation of the field.

**Comment by eliasnaur** [comment]
I don't think a link for fetching the UIView is necessary; users of ViewEvent can be assumed to have a good understanding of the UIKit, and accessing the UIView may not even be the most common use of ViewEvent.

Merged with a commit message tweak that makes it clear that ViewController is a replacement for View.

**Pull request closed without merging**
