### PR TITLE
io/pointer: [wasm] add missing cursors

### PR DESCRIPTION
**Pull request by Inkeliz**
Signed-off-by: Inkeliz <inkeliz@inkeliz.com>

### CODE REVIEW

**Comment by Inkeliz** [comment]
I rename the cursors because it's used directly on JS:

https://github.com/gioui/gio/blob/bed5902476c408308230c4d4dfb53e81d4ca1a6e/app/os_js.go#L548-L551

Maybe should it change to `switch` or add some comments in the commit (or in the code)?

**Comment by eliasnaur** [comment]
> I rename the cursors because it's used directly on JS:
> 
> https://github.com/gioui/gio/blob/bed5902476c408308230c4d4dfb53e81d4ca1a6e/app/os_js.go#L548-L551
> 
> Maybe should it change to `switch` or add some comments in the commit (or in the code)?

The names shouldn't be dictated by a platform, but I like that the cursor names match layout.Direction, and there's a slight advantage in using names commonly known from JS. WDYT, @pierrec?

**Comment by eliasnaur** [comment]
Either way, the patch needs rebasing.

**Comment by pierrec** [comment]
@eliasnaur @Inkeliz I also like the names matching Direction.

**Comment by eliasnaur** [comment]
Thanks, Pierre. @Inkeliz please rebase your change and I'll merge it.

**Comment by eliasnaur** [comment]
Thanks, merged.

**Pull request closed without merging**
