### PR TITLE
app/internal/window,cmd/gogio: fix golint issues and sort imports using goimports

### PR DESCRIPTION
**Pull request by mewmew**
Golint issues:

	app/internal/window/os_wayland.go:1448:12: gioui.org/io/system.StageEvent composite literal uses unkeyed fields
	app/internal/window/os_x11.go:183:12: gioui.org/io/system.StageEvent composite literal uses unkeyed fields

Goimports command:

	find gio/ -type f -name '*.go' | xargs -I '{}' goimports -w '{}'

---

**Note:** This PR is intended to assess the Gio Sourcehut/GitHub integration. It contains no functional code changes, only stylistic.

Preferably, Gio would be able to employ similar collaboration synchronization tools as those employed by the official Go project, which would enable automatically creating Sourcehut patches for corresponding GitHub PRs made to the Gio mirror repository.

Thusly, consider this PR not as a suggestion for code change to Gio, it may very well be ignored and closed. Consider it instead a test of the integration bridge between the Sourcehut Gio repository and the GitHub Gio mirror repository.

Cheers,
Robin

### CODE REVIEW

**Comment by whereswaldon** [comment]
@mewmew Is the GitHub => SourceHut integration doing what you expect?

The Linux CI failed because your commits aren't signed-off.

**Comment by mewmew** [comment]
> The Linux CI failed because your commits aren't signed-off.

I tried signing the commits, perhaps we'd need to re-run the CI

**Comment by whereswaldon** [comment]
@mewmew The nomenclature is confusing. What I mean is, your commits need a line that indicates your acceptance of the Gio license for your contributions. This takes the form of a line at the end of your commit message of the form "Signed-off By: FirstName LastName <email>". All commits that are merged are required to have this.

Git can actually insert that line for you if you use the `-s` flag on `git commit`. `git commit -sm "message"` creates a signed-off commit with the given message. To fix your current PR, try this:

`git rebase -i HEAD~3`
Mark each commit you made in this PR as `e` for `edit`
`git commit -s --amend`
`git rebase --continue`
`git commit -s --amend`
`git rebase --continue`

Something approximately like that should do the trick. Then force-push to this branch.

This is an independent idea from cryptographically signing your commits. I know that's super confusing. Sorry!

**Comment by mewmew** [comment]
@whereswaldon Thanks for taking the time to explain. Now it's much clearer, and I see the overlap of terminology.

I just pushed the signed-off commits. Hopefully it should work this time.

**Comment by mewmew** [comment]
> @mewmew Is the GitHub => SourceHut integration doing what you expect?

I'd say it depends :) Personally, I'd be very happy if it was possible to submit PRs towards the Gio GitHub mirror repository, and have them be automatically integrated into the regular development pipeline of the Gio project. Similar to how PRs submitted towards the Go GitHub mirror are automatically converted to Gerrit changelists.

This would enable contributions to Gio from users who are "locked into" GitHub for their day-to-day workflow, while hopefully not removing any substantial time from Gio main contributors if these code changes were integrated into their preferred day-to-day workflow; e.g. Sourcehut patches.

**Comment by eliasnaur** [comment]
@mewmew I'd like the PRs mailed as well, to make the difference between PRs and sr.ht patches smaller. I've filed https://todo.sr.ht/~sircmpwn/dispatch.sr.ht/46.
In the meantime, this workflow is smooth enough for me: I can `git pull mirror pull/<PR#>/head` and submit from the command line, and GH is clever enough to automatically close the PR when its mirror is force pushed.

**Comment by mewmew** [comment]
While this is definitely not the *right* place to post issues, let alone on an unrelated PR, it does highlight a point I'll be trying to make.

I noticed an issue today when browsing through the documentation at https://gioui.org/, namely that the GoDoc.org links are broken. For instance, https://godoc.org/gioui.org/io/key returns 404. The corresponding pkg.go.dev links work though.

I wanted to submit a quick issue to gioui/gio through GitHub, but now noticed that only pull requests are enabled for this repository. While I understand the which to collect all issues under a single issue tracker it also makes the threshold for contributing issue tickets higher, at least for non-source hut users. For me personally, I would not wish to send an email to create an issue, partly because I would like to limit the expose of my private email address on the Internet (in part to limit spam).

So, for this reason, I would like to submit for consideration the notion of opening up the issue functionality of the `gioui/gio` repo on GitHub. Preferably, the issues posted on the GitHub mirror repo of gio could be automatically mirrored to the SourceHut gio project todo issue mailing list, in a similar fashion as mirroring of PRs (https://todo.sr.ht/~sircmpwn/dispatch.sr.ht/46).

Once more, I know this is not the right forum to start these discussions (in an unrelated PR on GitHub), so feel free to copy this message to the Gio mailing list.

Cheers,
Robin

**Comment by eliasnaur** [comment]
> While this is definitely **not** the _right_ place to post issues, let alone on an unrelated PR, it does highlight a point I'll be trying to make.
> 
> I noticed an issue today when browsing through the documentation at https://gioui.org/, namely that the GoDoc.org links are broken. For instance, https://godoc.org/gioui.org/io/key returns 404. The corresponding pkg.go.dev links work though.
> 

Thanks for letting us know. The links are fixed as of [b31d0ed80584](https://git.sr.ht/~eliasnaur/giouiorg/commit/b31d0ed80584e00909450eafa26a6198d66b6b9e).

> I wanted to submit a quick issue to gioui/gio through GitHub, but now noticed that only pull requests are enabled for this repository. While I understand the which to collect all issues under a single issue tracker it also makes the threshold for contributing issue tickets higher, at least for non-source hut users. For me personally, I would not wish to send an email to create an issue, partly because I would like to limit the expose of my private email address on the Internet (in part to limit spam).
> 

Please feel free to mail me directly at mail@eliasnaur.com for further inquiries and issues. Please note that todo.sr.ht does support creating issues without revealing your email address, provided you create a sr.ht account.

> So, for this reason, I would like to submit for consideration the notion of opening up the issue functionality of the `gioui/gio` repo on GitHub. Preferably, the issues posted on the GitHub mirror repo of gio could be automatically mirrored to the SourceHut gio project todo issue mailing list, in a similar fashion as mirroring of PRs (https://todo.sr.ht/~sircmpwn/dispatch.sr.ht/46).
> 

(I'll note that dispatch.sr.ht issue 46 is not implemented).

I'm skeptical that bifurcating the issue tracker across sr.ht and github is a good idea. Issues are often long lived and contain valuable discussion and history, similar to the project mailing list. Pull requests, on the other hand, are usually much more focused and quicker to resolve. PRs may contain interesting discussion, but most of that (should) end up in the PR itself (commit message and/or code).

That said, if someone comes up with a smooth mirroring facility where every issue is automatically two-way mirrored, I would be open to at least experiment with a GitHub issue tracker.

**Comment by whereswaldon** [comment]
It's not two way, but I know of a GitHub action that will automatically post the content of a GitHub issue into a sourcehut issue tracker. It responds to the person who opened the issue in GitHub asking for them to continue the conversation on the sourcehut tracker. https://github.com/aThorp96/sourcehut_issue_mirror

**Comment by mewmew** [comment]
> It's not two way, but I know of a GitHub action that will automatically post the content of a GitHub issue into a sourcehut issue tracker. It responds to the person who opened the issue in GitHub asking for them to continue the conversation on the sourcehut tracker. https://github.com/aThorp96/sourcehut_issue_mirror

Sounds like a great start for integrating communication between these two platforms.

**Pull request merged**
