### PR TITLE
app/internal/window: fix support for Safari 11.1

### PR DESCRIPTION
**Pull request by Inkeliz**

### CODE REVIEW

**Comment by eliasnaur** [comment]
Thanks! Merged.

**Comment by Inkeliz** [comment]
It get's merged, but doesn't closes the PR. 👀

**Comment by eliasnaur** [comment]
Can't explain why :/

**Comment by whereswaldon** [comment]
@eliasnaur The auto-close feature will only work if you don't change the commit hash as part of merging the commit. The commit in this PR has hash `8123`, but the version in `main`'s history has a different hash. GitHub can't tell they're the same, so I think this is expected behavior.

**Pull request closed without merging**
